version: '3.4'

services:
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pepsi
  
  healthapploginservice:
    container_name: helath_app_login_service
    environment:
        - EASYNETQ_CONNECTION_STRING=host=rabbitmq;port=5672;virtualHost=/;username=application;password=pepsi
    build:
        context: .
        dockerfile: Health App Login/Dockerfile
    networks:
        - microservices_net
  HealthAppApi:
    build:
      context: .
      dockerfile: Health App Api/Dockerfile
    deploy:
      replicas: 2

networks:
    microservices_net:
        external: true

volumes:
  rps_seq_data: